services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    volumes:
      - wp_volume:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - bridge-network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress/
    volumes:
      - wp_volume:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis
    build: ./requirements/bonus/redis/
    volumes:
      - redis_volume:/data
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

  ftp:
    container_name: ftp
    image: ftp
    build: ./requirements/bonus/ftp/
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp_volume:/var/www/html
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/bonus/adminer/
    ports:
      - "9000:9000"
    restart: always
    networks:
      - bridge-network
    volumes:
      - adminer_volume:/data

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none
  adminer_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none
  redis_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none

networks:
  bridge-network:
    driver: bridge
